In [61]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import random

In [62]:
dir_path = ''
df = pd.read_pickle(dir_path+'df_hourly_BTC.pickle')
df

USDT_BTC_high  USDT_BTC_low  USDT_BTC_close  \
time                                                               
2016-01-02 12:00:00     432.500000    432.500000      432.500000   
2016-01-02 13:00:00     432.500000    432.500000      432.500000   
2016-01-02 14:00:00     437.363500    432.480000      433.340000   
2016-01-02 15:00:00     432.480000    432.480000      432.480000   
2016-01-02 16:00:00     432.480000    432.480000      432.480000   
2016-01-02 17:00:00     432.480000    432.220000      432.220000   
2016-01-02 18:00:00     432.220000    432.220000      432.220000   
2016-01-02 19:00:00     432.220000    432.220000      432.220000   
2016-01-02 20:00:00     432.220000    432.220000      432.220000   
2016-01-02 21:00:00     436.949900    432.220000      436.949900   
2016-01-02 22:00:00     436.949900    436.949900      436.949900   
2016-01-02 23:00:00     436.949900    436.949900      436.949900   
2016-01-03 00:00:00     436.949900    436.949900      436.949900   
2016-01-03 01:00:00     436.949900    436.949900      436.949900   
2016-01-03 02:00:00     436.949900    432.310000      435.614998   
2016-01-03 03:00:00     435.614998    430.490000      430.490000   
2016-01-03 04:00:00     431.450000    430.490000      430.490000   
2016-01-03 05:00:00     435.127280    429.000000      435.127280   
2016-01-03 06:00:00     435.127280    435.127280      435.127280   
2016-01-03 07:00:00     435.127280    435.127280      435.127280   
2016-01-03 08:00:00     435.127280    435.127280      435.127280   
2016-01-03 09:00:00     429.000000    426.453089      429.000000   
2016-01-03 10:00:00     429.000000    429.000000      429.000000   
2016-01-03 11:00:00     429.000000    426.453091      427.300000   
2016-01-03 12:00:00     427.300000    427.300000      427.300000   
2016-01-03 13:00:00     429.860000    427.300000      429.000000   
2016-01-03 14:00:00     429.000000    429.000000      429.000000   
2016-01-03 15:00:00     427.300000    427.300000      427.300000   
2016-01-03 16:00:00     427.300000    427.300000      427.300000   
2016-01-03 17:00:00     427.300000    427.292635      427.292635   
...                            ...           ...             ...   
2018-04-12 22:00:00    7873.161816   7749.359305     7861.923694   
2018-04-12 23:00:00    7985.316951   7840.502294     7929.999999   
2018-04-13 00:00:00    7990.000000   7810.200000     7881.941983   
2018-04-13 01:00:00    7899.684525   7735.891673     7790.000000   
2018-04-13 02:00:00    7891.000000   7784.686705     7889.633850   
2018-04-13 03:00:00    7908.164386   7810.000000     7828.514201   
2018-04-13 04:00:00    7839.854980   7788.698808     7824.000000   
2018-04-13 05:00:00    7831.538793   7769.000000     7800.617365   
2018-04-13 06:00:00    7888.000000   7800.316572     7836.005559   
2018-04-13 07:00:00    8179.982263   7820.102628     8095.780598   
2018-04-13 08:00:00    8148.775120   8058.017104     8130.000000   
2018-04-13 09:00:00    8156.262105   8052.700001     8052.700001   
2018-04-13 10:00:00    8095.600000   8006.470817     8061.330027   
2018-04-13 11:00:00    8159.056298   8047.383891     8094.000000   
2018-04-13 12:00:00    8220.524434   8089.896108     8196.986438   
2018-04-13 13:00:00    8230.000000   8029.905987     8089.174841   
2018-04-13 14:00:00    8129.594299   8030.078480     8108.552578   
2018-04-13 15:00:00    8133.965474   8080.317104     8132.139999   
2018-04-13 16:00:00    8168.089319   8081.100000     8126.770000   
2018-04-13 17:00:00    8166.856081   8050.000000     8112.124286   
2018-04-13 18:00:00    8124.825157   8075.051315     8103.200000   
2018-04-13 19:00:00    8140.816404   8054.000000     8101.261638   
2018-04-13 20:00:00    8101.278742   7850.000000     7904.000372   
2018-04-13 21:00:00    7940.382896   7845.000000     7874.000000   
2018-04-13 22:00:00    7912.606123   7801.000000     7910.781137   
2018-04-13 23:00:00    7966.073112   7860.669160     7875.000000   
2018-04-1

In [63]:
from scipy import stats
def find_bin(df,col_name,bin_num,is_pct_change):
    filled = df[col_name]
    if is_pct_change:
        filled = filled.pct_change()
        df[col_name + str("_pctChange")] = filled.copy()
        filled = filled.iloc[1:]
    print(filled.max())
    print(filled.min())
#     print(filled.isnull())
    bin_edges = stats.mstats.mquantiles(filled, [x/bin_num for x in range(bin_num + 1)])
    print(bin_edges)
    return bin_edges

In [64]:
def create_label(df,col_name,need_pctChange):
    bin_edges = find_bin(df,col_name,3,need_pctChange)
    if (need_pctChange):
        labels = df[col_name+str("_pctChange")].copy()
    else:
        labels = df[col_name].copy()
    idx0 = (labels <= bin_edges[1])
    idx1 = (labels >= bin_edges[2])
    idx2 = ((labels < bin_edges[2]) & (labels>bin_edges[1]))
    labels[idx0] = 0
    print(len(labels[labels == 0]))
    labels[idx1] = 2
    print(len(labels[labels == 2]))
    labels[idx2] = 1
    print(len(labels[labels == 1]))
    df[col_name+str('_label')] = labels

In [65]:
create_label(df,"USDT_BTC_pctChange",False)
# print()
create_label(df,"USDT_BTC_high", True)
create_label(df,"USDT_BTC_low", True)
create_label(df,"USDT_BTC_close", True)
create_label(df,"USDT_BTC_open",True)
create_label(df,"USDT_BTC_volatility", False)
df

0.09932744969207152
-0.14296119435136978
[-0.14296119 -0.00155635  0.00226021  0.09932745]
6668
6661
6662
0.15344993311771993
-0.12450069183987733
[-0.12450069 -0.00134754  0.00118713  0.15344993]
7686
6661
6661
0.13863532046875005
-0.20508744050793515
[-0.20508744 -0.00066254  0.00202188  0.13863532]
7579
6661
6661
0.12093023255813962
-0.1375610486796437
[-0.13756105 -0.00194451  0.00248945  0.12093023]
7006
6661
6661
0.12093023255481739
-0.13728632489692905
[-0.13728632 -0.00188304  0.00245898  0.12093023]
6984
6661
6661
0.06401832373659477
0.0
[0.         0.00191669 0.00323811 0.06401832]
6661
6661
6662


USDT_BTC_high  USDT_BTC_low  USDT_BTC_close  \
time                                                               
2016-01-02 12:00:00     432.500000    432.500000      432.500000   
2016-01-02 13:00:00     432.500000    432.500000      432.500000   
2016-01-02 14:00:00     437.363500    432.480000      433.340000   
2016-01-02 15:00:00     432.480000    432.480000      432.480000   
2016-01-02 16:00:00     432.480000    432.480000      432.480000   
2016-01-02 17:00:00     432.480000    432.220000      432.220000   
2016-01-02 18:00:00     432.220000    432.220000      432.220000   
2016-01-02 19:00:00     432.220000    432.220000      432.220000   
2016-01-02 20:00:00     432.220000    432.220000      432.220000   
2016-01-02 21:00:00     436.949900    432.220000      436.949900   
2016-01-02 22:00:00     436.949900    436.949900      436.949900   
2016-01-02 23:00:00     436.949900    436.949900      436.949900   
2016-01-03 00:00:00     436.949900    436.949900      436.949900   
2016-01-03 01:00:00     436.949900    436.949900      436.949900   
2016-01-03 02:00:00     436.949900    432.310000      435.614998   
2016-01-03 03:00:00     435.614998    430.490000      430.490000   
2016-01-03 04:00:00     431.450000    430.490000      430.490000   
2016-01-03 05:00:00     435.127280    429.000000      435.127280   
2016-01-03 06:00:00     435.127280    435.127280      435.127280   
2016-01-03 07:00:00     435.127280    435.127280      435.127280   
2016-01-03 08:00:00     435.127280    435.127280      435.127280   
2016-01-03 09:00:00     429.000000    426.453089      429.000000   
2016-01-03 10:00:00     429.000000    429.000000      429.000000   
2016-01-03 11:00:00     429.000000    426.453091      427.300000   
2016-01-03 12:00:00     427.300000    427.300000      427.300000   
2016-01-03 13:00:00     429.860000    427.300000      429.000000   
2016-01-03 14:00:00     429.000000    429.000000      429.000000   
2016-01-03 15:00:00     427.300000    427.300000      427.300000   
2016-01-03 16:00:00     427.300000    427.300000      427.300000   
2016-01-03 17:00:00     427.300000    427.292635      427.292635   
...                            ...           ...             ...   
2018-04-12 22:00:00    7873.161816   7749.359305     7861.923694   
2018-04-12 23:00:00    7985.316951   7840.502294     7929.999999   
2018-04-13 00:00:00    7990.000000   7810.200000     7881.941983   
2018-04-13 01:00:00    7899.684525   7735.891673     7790.000000   
2018-04-13 02:00:00    7891.000000   7784.686705     7889.633850   
2018-04-13 03:00:00    7908.164386   7810.000000     7828.514201   
2018-04-13 04:00:00    7839.854980   7788.698808     7824.000000   
2018-04-13 05:00:00    7831.538793   7769.000000     7800.617365   
2018-04-13 06:00:00    7888.000000   7800.316572     7836.005559   
2018-04-13 07:00:00    8179.982263   7820.102628     8095.780598   
2018-04-13 08:00:00    8148.775120   8058.017104     8130.000000   
2018-04-13 09:00:00    8156.262105   8052.700001     8052.700001   
2018-04-13 10:00:00    8095.600000   8006.470817     8061.330027   
2018-04-13 11:00:00    8159.056298   8047.383891     8094.000000   
2018-04-13 12:00:00    8220.524434   8089.896108     8196.986438   
2018-04-13 13:00:00    8230.000000   8029.905987     8089.174841   
2018-04-13 14:00:00    8129.594299   8030.078480     8108.552578   
2018-04-13 15:00:00    8133.965474   8080.317104     8132.139999   
2018-04-13 16:00:00    8168.089319   8081.100000     8126.770000   
2018-04-13 17:00:00    8166.856081   8050.000000     8112.124286   
2018-04-13 18:00:00    8124.825157   8075.051315     8103.200000   
2018-04-13 19:00:00    8140.816404   8054.000000     8101.261638   
2018-04-13 20:00:00    8101.278742   7850.000000     7904.000372   
2018-04-13 21:00:00    7940.382896   7845.000000     7874.000000   
2018-04-13 22:00:00    7912.606123   7801.000000     7910.781137   
2018-04-13 23:00:00    7966.073112   7860.669160     7875.000000   
2018-04-1

In [74]:
df.to_pickle('df_hourly_BTC_with_labels.pickle')

In [29]:
find_bin(df,"USDT_BTC_low",3,True)

0.13863532046875005
-0.20508744050793515
[-0.20508744 -0.00066254  0.00202188  0.13863532]


In [70]:
find_bin(df,"USDT_BTC_close",3,True)

0.12093023255813962
-0.1375610486796437
[-0.13756105 -0.00194451  0.00248945  0.12093023]


array([-0.13756105, -0.00194451,  0.00248945,  0.12093023])

In [71]:
find_bin(df,"USDT_BTC_open",3,True)

0.12093023255481739
-0.13728632489692905
[-0.13728632 -0.00188304  0.00245898  0.12093023]


array([-0.13728632, -0.00188304,  0.00245898,  0.12093023])

In [33]:
find_bin(df,"USDT_BTC_volatility",3,False)

0.06401832373659477
0.0
[0.         0.00191669 0.00323811 0.06401832]


In [35]:
find_bin(df,"USDT_BTC_volume",3,False)

46657847.01134279
0.0
[0.00000000e+00 1.18536426e+04 7.51860815e+05 4.66578470e+07]


In [41]:
find_bin(df,"USDT_BTC_weighted_mean",3,True)

0.09932744969207152
-0.14296119435136978
[-0.14296119 -0.00155688  0.00226024  0.09932745]


In [60]:
find_bin(df,"USDT_BTC_pctChange",3,False)

0.09932744969207152
-0.14296119435136978
[-0.14296119 -0.00155635  0.00226021  0.09932745]


array([-0.14296119, -0.00155635,  0.00226021,  0.09932745])

In [69]:
df[df['USDT_BTC_close'] != df['USDT_BTC_open']]

USDT_BTC_high  USDT_BTC_low  USDT_BTC_close  \
time                                                               
2016-01-02 14:00:00     437.363500    432.480000      433.340000   
2016-01-02 17:00:00     432.480000    432.220000      432.220000   
2016-01-02 21:00:00     436.949900    432.220000      436.949900   
2016-01-03 02:00:00     436.949900    432.310000      435.614998   
2016-01-03 03:00:00     435.614998    430.490000      430.490000   
2016-01-03 05:00:00     435.127280    429.000000      435.127280   
2016-01-03 09:00:00     429.000000    426.453089      429.000000   
2016-01-03 11:00:00     429.000000    426.453091      427.300000   
2016-01-03 12:00:00     427.300000    427.300000      427.300000   
2016-01-03 13:00:00     429.860000    427.300000      429.000000   
2016-01-03 17:00:00     427.300000    427.292635      427.292635   
2016-01-03 18:00:00     427.721289    427.290000      427.290000   
2016-01-03 21:00:00     428.140000    427.290000      428.140000   
2016-01-04 02:00:00     428.140000    427.291140      427.300000   
2016-01-04 03:00:00     429.140000    427.300000      428.999000   
2016-01-04 04:00:00     429.999000    429.140000      429.999000   
2016-01-04 05:00:00     429.999000    429.569500      429.569500   
2016-01-04 07:00:00     435.679577    429.569500      435.679577   
2016-01-04 08:00:00     435.679577    429.570011      429.570011   
2016-01-04 09:00:00     429.570011    429.570000      429.570000   
2016-01-04 11:00:00     429.935770    429.569500      429.569500   
2016-01-04 12:00:00     430.800000    429.569500      429.999751   
2016-01-04 13:00:00     435.544163    429.999751      430.430000   
2016-01-04 14:00:00     430.430000    429.569500      429.569500   
2016-01-04 15:00:00     435.999999    429.569500      435.999999   
2016-01-04 17:00:00     435.999999    430.999616      430.999616   
2016-01-04 18:00:00     430.999719    430.999616      430.999719   
2016-01-04 19:00:00     430.999719    430.140025      430.140025   
2016-01-04 20:00:00     435.130000    430.140025      435.130000   
2016-01-04 21:00:00     435.999990    435.130000      435.999990   
...                            ...           ...             ...   
2018-04-12 22:00:00    7873.161816   7749.359305     7861.923694   
2018-04-12 23:00:00    7985.316951   7840.502294     7929.999999   
2018-04-13 00:00:00    7990.000000   7810.200000     7881.941983   
2018-04-13 01:00:00    7899.684525   7735.891673     7790.000000   
2018-04-13 02:00:00    7891.000000   7784.686705     7889.633850   
2018-04-13 03:00:00    7908.164386   7810.000000     7828.514201   
2018-04-13 04:00:00    7839.854980   7788.698808     7824.000000   
2018-04-13 05:00:00    7831.538793   7769.000000     7800.617365   
2018-04-13 06:00:00    7888.000000   7800.316572     7836.005559   
2018-04-13 07:00:00    8179.982263   7820.102628     8095.780598   
2018-04-13 08:00:00    8148.775120   8058.017104     8130.000000   
2018-04-13 09:00:00    8156.262105   8052.700001     8052.700001   
2018-04-13 10:00:00    8095.600000   8006.470817     8061.330027   
2018-04-13 11:00:00    8159.056298   8047.383891     8094.000000   
2018-04-13 12:00:00    8220.524434   8089.896108     8196.986438   
2018-04-13 13:00:00    8230.000000   8029.905987     8089.174841   
2018-04-13 14:00:00    8129.594299   8030.078480     8108.552578   
2018-04-13 15:00:00    8133.965474   8080.317104     8132.139999   
2018-04-13 16:00:00    8168.089319   8081.100000     8126.770000   
2018-04-13 17:00:00    8166.856081   8050.000000     8112.124286   
2018-04-13 18:00:00    8124.825157   8075.051315     8103.200000   
2018-04-13 19:00:00    8140.816404   8054.000000     8101.261638   
2018-04-13 20:00:00    8101.278742   7850.000000     7904.000372   
2018-04-13 21:00:00    7940.382896   7845.000000     7874.000000   
2018-04-13 22:00:00    7912.606123   7801.000000     7910.781137   
2018-04-13 23:00:00    7966.073112   7860.669160     7875.000000   
2018-04-1

In [6]:
df

USDT_BTC_high  USDT_BTC_low  USDT_BTC_close  \
time                                                               
2016-01-02 12:00:00     432.500000    432.500000      432.500000   
2016-01-02 13:00:00     432.500000    432.500000      432.500000   
2016-01-02 14:00:00     437.363500    432.480000      433.340000   
2016-01-02 15:00:00     432.480000    432.480000      432.480000   
2016-01-02 16:00:00     432.480000    432.480000      432.480000   
2016-01-02 17:00:00     432.480000    432.220000      432.220000   
2016-01-02 18:00:00     432.220000    432.220000      432.220000   
2016-01-02 19:00:00     432.220000    432.220000      432.220000   
2016-01-02 20:00:00     432.220000    432.220000      432.220000   
2016-01-02 21:00:00     436.949900    432.220000      436.949900   
2016-01-02 22:00:00     436.949900    436.949900      436.949900   
2016-01-02 23:00:00     436.949900    436.949900      436.949900   
2016-01-03 00:00:00     436.949900    436.949900      436.949900   
2016-01-03 01:00:00     436.949900    436.949900      436.949900   
2016-01-03 02:00:00     436.949900    432.310000      435.614998   
2016-01-03 03:00:00     435.614998    430.490000      430.490000   
2016-01-03 04:00:00     431.450000    430.490000      430.490000   
2016-01-03 05:00:00     435.127280    429.000000      435.127280   
2016-01-03 06:00:00     435.127280    435.127280      435.127280   
2016-01-03 07:00:00     435.127280    435.127280      435.127280   
2016-01-03 08:00:00     435.127280    435.127280      435.127280   
2016-01-03 09:00:00     429.000000    426.453089      429.000000   
2016-01-03 10:00:00     429.000000    429.000000      429.000000   
2016-01-03 11:00:00     429.000000    426.453091      427.300000   
2016-01-03 12:00:00     427.300000    427.300000      427.300000   
2016-01-03 13:00:00     429.860000    427.300000      429.000000   
2016-01-03 14:00:00     429.000000    429.000000      429.000000   
2016-01-03 15:00:00     427.300000    427.300000      427.300000   
2016-01-03 16:00:00     427.300000    427.300000      427.300000   
2016-01-03 17:00:00     427.300000    427.292635      427.292635   
...                            ...           ...             ...   
2018-04-12 22:00:00    7873.161816   7749.359305     7861.923694   
2018-04-12 23:00:00    7985.316951   7840.502294     7929.999999   
2018-04-13 00:00:00    7990.000000   7810.200000     7881.941983   
2018-04-13 01:00:00    7899.684525   7735.891673     7790.000000   
2018-04-13 02:00:00    7891.000000   7784.686705     7889.633850   
2018-04-13 03:00:00    7908.164386   7810.000000     7828.514201   
2018-04-13 04:00:00    7839.854980   7788.698808     7824.000000   
2018-04-13 05:00:00    7831.538793   7769.000000     7800.617365   
2018-04-13 06:00:00    7888.000000   7800.316572     7836.005559   
2018-04-13 07:00:00    8179.982263   7820.102628     8095.780598   
2018-04-13 08:00:00    8148.775120   8058.017104     8130.000000   
2018-04-13 09:00:00    8156.262105   8052.700001     8052.700001   
2018-04-13 10:00:00    8095.600000   8006.470817     8061.330027   
2018-04-13 11:00:00    8159.056298   8047.383891     8094.000000   
2018-04-13 12:00:00    8220.524434   8089.896108     8196.986438   
2018-04-13 13:00:00    8230.000000   8029.905987     8089.174841   
2018-04-13 14:00:00    8129.594299   8030.078480     8108.552578   
2018-04-13 15:00:00    8133.965474   8080.317104     8132.139999   
2018-04-13 16:00:00    8168.089319   8081.100000     8126.770000   
2018-04-13 17:00:00    8166.856081   8050.000000     8112.124286   
2018-04-13 18:00:00    8124.825157   8075.051315     8103.200000   
2018-04-13 19:00:00    8140.816404   8054.000000     8101.261638   
2018-04-13 20:00:00    8101.278742   7850.000000     7904.000372   
2018-04-13 21:00:00    7940.382896   7845.000000     7874.000000   
2018-04-13 22:00:00    7912.606123   7801.000000     7910.781137   
2018-04-13 23:00:00    7966.073112   7860.669160     7875.000000   
2018-04-1

In [73]:
len(df[df["USDT_BTC_pctChange_label"] == 0])

6661